### PR TITLE
fix: add missing items from genesis

### LINKED ISSUE #220: Unable to set chainId in geth --dev genesis config
### What happened?

to get the new geth and py-geth to work in Ape, I had to make a silly edition to the code:

```python
class GenesisDataConfig(BaseModel):
    chainId: int = 0
    ...
```

just adds chain ID.
Otherwise, my transactions were all failing with `Invalid sender` for my accounts.
With this change, I can set the chain Id and make transactions in my dev environment whilst overriding the genesis...

Perhaps there is an alternative in the meantime I am unaware of?

### Code that produced the error

```python
Alloc = dict[str, dict[str, Any]]


def create_genesis_data(alloc: Alloc, chain_id: int) -> GenesisDataTypedDict:
    """
    A wrapper around genesis data for py-geth that
    fills in more defaults.
    """
    return {
        "alloc": alloc,
        "config": {
            "arrowGlacierBlock": 0,
            "berlinBlock": 0,
            "byzantiumBlock": 0,
            "cancunTime": 0,
            "chainId": chain_id,
            "constantinopleBlock": 0,
            "daoForkBlock": 0,
            "daoForkSupport": True,
            "eip150Block": 0,
            "eip155Block": 0,
            "eip158Block": 0,
            "ethash": {},
            "grayGlacierBlock": 0,
            "homesteadBlock": 0,
            "istanbulBlock": 0,
            "londonBlock": 0,
            "petersburgBlock": 0,
            "shanghaiTime": 0,
            "terminalTotalDifficulty": 0,
            "terminalTotalDifficultyPassed": True,
        },
        "coinbase": ZERO_ADDRESS,
        "difficulty": "0x0",
        "extraData": "0x",
        "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "nonce": "0x0",
        "timestamp": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    }


class GethDevProcess(BaseGethProcess):
    """
    A developer-configured geth that only exists until disconnected.
    """

    def __init__(
        self,
        data_dir: Path,
        hostname: str = DEFAULT_HOSTNAME,
        port: int = DEFAULT_PORT,
        mnemonic: str = DEFAULT_TEST_MNEMONIC,
        number_of_accounts: int = DEFAULT_NUMBER_OF_TEST_ACCOUNTS,
        chain_id: int = DEFAULT_TEST_CHAIN_ID,
        initial_balance: Union[str, int] = to_wei(10000, "ether"),
        executable: Optional[str] = None,
        auto_disconnect: bool = True,
        extra_funded_accounts: Optional[list[str]] = None,
        hd_path: Optional[str] = DEFAULT_TEST_HD_PATH,
    ):
        executable = executable or "geth"
        if not shutil.which(executable):
            raise NodeSoftwareNotInstalledError()

        self._data_dir = data_dir
        self._hostname = hostname
        self._port = port
        self._data_dir.mkdir(exist_ok=True, parents=True)
        self.is_running = False
        self._auto_disconnect = auto_disconnect

        geth_kwargs = construct_test_chain_kwargs(
            data_dir=self.data_dir,
            geth_executable=executable,
            rpc_addr=hostname,
            rpc_port=f"{port}",
            network_id=f"{chain_id}",
            ws_enabled=False,
            ws_addr=None,
            ws_origins=None,
            ws_port=None,
            ws_api=None,
        )

        # Ensure a clean data-dir.
        self._clean()

        # sealer = ensure_account_exists(**geth_kwargs).replace("0x", "")
        # geth_kwargs["miner_etherbase"] = sealer
        geth_kwargs["dev_mode"] = True
        accounts = generate_dev_accounts(
            mnemonic, number_of_accounts=number_of_accounts, hd_path=hd_path or DEFAULT_TEST_HD_PATH
        )
        addresses = [a.address for a in accounts]
        addresses.extend(extra_funded_accounts or [])
        bal_dict = {"balance": str(initial_balance)}
        alloc = {a: bal_dict for a in addresses}
        genesis = create_genesis_data(alloc, chain_id)
        self._data_dir.mkdir(parents=True, exist_ok=True)
        initialize_chain(genesis, self.data_dir)
        super().__init__(geth_kwargs)
```

### Full error output

```shell
geth.exceptions.PyGethValueError: genesis_data config field validation failed: 1 validation error for GenesisDataConfig
E               chainId
E                 Extra inputs are not permitted [type=extra_forbidden, input_value=1337, input_type=int]
E                   For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden


but if i exclude chainId i got this:

(-32000) invalid sender
```

### Fill this section in if you know how this could or should be fixed

Allow chainId to be set on the model.
Doing this fixed the issue for me!

### py-geth Version

5.0.0b1

### Python Version

Python 3.12.2

### Operating System

macOS intel

### Output from `pip freeze`

```shell
i will paste if needed but it is not a pretty freeze.
```

### PR DESCRIPTION
**Pull request by antazoey**
### What was wrong?

Related to Issue #220
Closes #220

mostly opening to show what I had to do to get it to work in Ape!

### How was it fixed?

add fields

### Todo:

- [x] Clean up commit history
- [x] Add or update documentation related to these changes
- [x] Add entry to the [release notes](https://github.com/ethereum/py-geth/blob/main/newsfragments/README.md)

#### Cute Animal Picture

◡̈   <--- it's an ape!

### CODE REVIEW

**Comment by kclowes** [comment]
Thanks for the PR! I added a few more that I noticed were missing.

**Comment by kclowes** [comment]
@antazoey I also changed `mixhash` -> `mixHash` to match geth, let me know if that throws you off and I'll change it back!

**Comment by antazoey** [comment]
> @antazoey I also changed `mixhash` -> `mixHash` to match geth, let me know if that throws you off and I'll change it back!

I had it that way before. So that works!

**Review by pacrob — APPROVED** [review]
lgtm!

**Pull request merged**
