### PR TITLE
Add geth versions from 1.8.2 to 1.8.22

### PR DESCRIPTION
**Pull request by Bhargavasomu**
### What was wrong?
Fixes Issue #46
Also this PR removes support of `geth versions <1.7`

### How was it fixed?
Added all the versions manually and also added them to the tests.

#### Cute Animal Picture

Put a cute animal picture here

### CODE REVIEW

**Comment by Bhargavasomu** [comment]
This is taking a lot of time to check for `Integration`. Going to give migration to `Circle CI` a shot. Will resume this after that.

**Comment by Bhargavasomu** [comment]
@pipermerriam please review this. The `Circle CI` is bloating with the different versions of `geth`. Shouldn't we remove testing some of the versions of `geth`. Seeing `config.yml` with 1000+ lines of code makes me feel bad about it. Please correct me if wrong.

**Comment by pipermerriam** [comment]
Yeah, seems reasonable to nuke everything before `<1.7`.

**Comment by Bhargavasomu** [comment]
@pipermerriam done. Please review now. The reason that I had to use `caches` from `v4` or `v5` is because that I messed up with `cache v1, v2, v3` and don't know how to delete them from `Circle CI` (I hope it can be done with the `Admin Acess` through the Circle CI UI, but not sure).

**Comment by pipermerriam** [comment]
Bumping cache numbers isn't a big deal.  no worries.

**Comment by Bhargavasomu** [comment]
It would be easier to remove the testing of the library in `python 2.7` if this gets merged first. So could this please get merged, if there aren't any further improvements to be made on this?

**Pull request merged**
